### ISSUE TITLE
Page 404 error

### ISSUE THREAD

**Issue by AyatoKirishima** [GeanyDuMal/AMT#11]
A adapter en twig 👌🏼

**Comment by AyatoKirishima** [comment]
a refaire

**Comment by AyatoKirishima** [comment]
adaptée et à tester

**Comment by Spl4shh** [comment]
a tester que ca fonctionne, prod mode ?

**Comment by AyatoKirishima** [comment]
ok elle fonctionne
juste pas de script pour les yeux
