### ISSUE TITLE
Compléter navbar

### ISSUE THREAD

**Issue by AyatoKirishima** [GeanyDuMal/AMT#20]
![image](https://user-images.githubusercontent.com/42692272/149657580-220182ac-a950-4084-a2f5-a80b604d0a38.png)

**Comment by AyatoKirishima** [comment]
product renvoie à profil

**Comment by AyatoKirishima** [comment]
![image](https://user-images.githubusercontent.com/42692272/149657612-5420bca1-c9bf-4a88-9c99-595c81dcef71.png)

@Dhoulnoun

**Comment by Spl4shh** [comment]
route pour product corriger reste a faire les autres

**Comment by Spl4shh** [comment]
Done
