### ISSUE TITLE
Taille img page accueil

### ISSUE THREAD

**Issue by AyatoKirishima** [GeanyDuMal/AMT#36]
a refaire

**Comment by Spl4shh** [comment]
Essayer d'ajouter le carrousel en page d'accueil ?

**Comment by Spl4shh** [comment]
Corrected a une specification : la taille de l'image quand l'ecran fait la taille d'un ecran de telephone mais que le site est en mode ordinateur

**Comment by Spl4shh** [comment]
corrected en augmentant la limite a laquelle onpasse en mode mobile
