### ISSUE TITLE
Footer Bottom

### ISSUE THREAD

**Issue by Spl4shh** [GeanyDuMal/AMT#38]
Sur certaines page, le footer a été fixé en position absolute mais si la page est blus grande, alors le footer reste planté au milieu de la page 

une des soluions : faire un bloc "content" qui fait 95vh de hauteur et mettre le footer en dessous (verifier dans profil, normalment fait a cet endroit la

**Comment by Spl4shh** [comment]
Peut etre faire en sorte que ca fonctionne sur la "base.html.twig" qu'on importe, et ensuite ne plus avoir a le gerer dans chacune des pages ?

**Comment by AyatoKirishima** [comment]
Pourquoi pas en faire un composant qu'on importe sur toutes les pages et qu'on ne modifie qu'une fois dans ce cas ?

--> C'est du javascript, c'est-à-dire pas ouffissime pour le seo mais il suffit de rajouter des liens cachés au cas où le js soit désactivé pour pallier ce problème

**Comment by Spl4shh** [comment]
Les composants sont disponibles sous forme de "block" avec twig, suffit de le creer dans la base mais je crois que c'est deja le cas, je pense que c'est plus une erreur de css : si la page fais plus de 100vh alors il se met tout en bas, sinon il se fixe a bottom : 0px

**Comment by AyatoKirishima** [comment]
Une solution serait de fixer une taille minimale au body ou a la div principale, comme ça, la page, même vide, aurait le footer en bas : comme [ici](https://projet-campagne-anti-harcelement.netlify.app/index.html)

**Comment by Spl4shh** [comment]
L'idée me parait bonne, a voir si c'est mettable en place de maniere générale dans la base qu'on importe
