### ISSUE TITLE
Mot de passe oublié

### ISSUE THREAD

**Issue by Spl4shh** [GeanyDuMal/AMT#47]
Proposer un moyen de résoudre le problème du mot de passe oublié, peut être un bouton qui permettrait de faire la demande a un admin ?

**Comment by Spl4shh** [comment]
devrait exiger des verifs afin de pouvoir envoyer la demande, peut etre check NOM + PRENOM + PSEUDO

**Comment by AyatoKirishima** [comment]
Voir si y'a des moyens déjà existants à la limite

**Comment by Spl4shh** [comment]
> Voir si y'a des moyens déjà existants à la limite

Le probleme etant que le login n'est pas un mail donc de nombreuse contrainte lié à comment transmettre le nouveau mot de passe ? Où ? Qui (Auto ou manuellement)?

**Comment by Spl4shh** [comment]
L'interface de contrôle pourrait aider :
Faire une table de demande de mot de passe en bd avec un client et une date
Ensuite dans l'interface possible de faire une attribution auto et de transmettre le mdp.
Réfléchir à cette idée

**Comment by Spl4shh** [comment]
Solution adoptée : 
Le client va faire une requête de mot de passe oubliée. Un code unique lui sera donné.
Ensuite il devra contacter un administrateur et lui transmettre le code. Si le code est correct, le mot de passe du client sera réinitialisé et ce dernier sera transmis a l'administrateur qui devra le transmettre au client.

Si le client oublie le code, il peut recréer une demande, un nouveau code lui sera transmis.


Cette solution est temporaire en attendant l'utilisation d'un service de mailling.
