### ISSUE TITLE
Vérification inputs

### ISSUE THREAD

**Issue by AyatoKirishima** [GeanyDuMal/AMT#7]
- [ ]  Faire en sorte d'avoir une vérif en temps réel
- [ ] Modif du texte (couleurs, check?)

![image](https://user-images.githubusercontent.com/42692272/147106640-84b0d432-8856-45e9-a032-f5cd9607c370.png)

**Comment by AyatoKirishima** [comment]
**https://gist.github.com/AyatoKirishima/a40c3080122eace4be16488b006456b0**

**Comment by Spl4shh** [comment]
Pas besoin de le faire avec le password strength car incomprehension sur ce qui est necessaire
