### ISSUE TITLE
Changement style pages connexion / login / profil

### ISSUE THREAD

**Issue by AyatoKirishima** [GeanyDuMal/AMT#8]
![image](https://user-images.githubusercontent.com/42692272/147250707-3e7fbd73-d471-4bbd-af68-cd42f2a10590.png)

**Comment by AyatoKirishima** [comment]
![image](https://user-images.githubusercontent.com/42692272/147262644-b6bb8835-0f3f-4ed4-b185-8ff5090a72dd.png)

**Comment by AyatoKirishima** [comment]
![image](https://user-images.githubusercontent.com/42692272/147262857-89356524-2b8e-4f7d-a84e-c90023366b28.png)

**Comment by AyatoKirishima** [comment]
![image](https://user-images.githubusercontent.com/42692272/147265867-bd37f527-7303-40f3-8a35-4c9d6f703259.png)

**Comment by AyatoKirishima** [comment]
![image](https://user-images.githubusercontent.com/42692272/147267365-53ec05f9-230f-4f70-af0f-a6ac973faeed.png)
![image](https://user-images.githubusercontent.com/42692272/147267374-1da5228d-2e3b-4cdf-ab25-93322c6bad8b.png)

**Comment by AyatoKirishima** [comment]
- [ ] probleme responsif
- [x] entete a ajouter sur 2 pages
- [x] sur la page inscription, le lien vers la page connexion est caché (pourquoi ? je ne sais pas)

![image](https://user-images.githubusercontent.com/42692272/147270805-06c01910-c70b-45a0-918a-17b56013619f.png)

![image](https://user-images.githubusercontent.com/42692272/147270902-c46868f2-0f26-4b0f-93f8-2cee999fc078.png)

![image](https://user-images.githubusercontent.com/42692272/147270986-8b4abd6c-a5ec-4261-8d2c-fdbdfd76d703.png)


@Spl4shh

**Comment by Spl4shh** [comment]
baisse la margin

**Comment by AyatoKirishima** [comment]
![image](https://user-images.githubusercontent.com/42692272/147406269-3ca30ba9-cc5c-40f7-adf1-fd8f55d4b3be.png)
![image](https://user-images.githubusercontent.com/42692272/147406275-803d5707-25e5-453e-9974-b764e2540473.png)

problème taille "header"

**Comment by AyatoKirishima** [comment]
![image](https://user-images.githubusercontent.com/42692272/147406388-caf28978-82cb-4c2f-9667-babe200d3184.png)
Problème de couleur de fond (& margin)

**Comment by AyatoKirishima** [comment]
![image](https://user-images.githubusercontent.com/42692272/147406427-71d263a8-c138-42c8-b36b-ca6b802aa6cc.png)
problem solved 
ça venait de l'html

**Comment by AyatoKirishima** [comment]
- [x] résoudre problème responsif

**Comment by AyatoKirishima** [comment]
![image](https://user-images.githubusercontent.com/42692272/147744666-cfbc0252-b75c-4202-803f-ef7712e72257.png)

👌🏼
