### ISSUE TITLE
[RGPD] - Pas aux normes 

### ISSUE THREAD

**Issue by AyatoKirishima** [GeanyDuMal/AMT#89]
- On doit pouvoir refuser les cookies
- Une politique de confidentialité doit être présente sur le site

**Comment by AyatoKirishima** [comment]
Axeptio pour les cookies

-> peut-être installé via gtm 
--> gtm peut-être relié à analytics
Une pierre deux coups ;)

**Comment by Spl4shh** [comment]
Les cookies tu peux ne pas les accepter, tu auras juste le bandeau jaune en bas en permanence si je ne dit pas de bêtise.
Le service des cookies n'est pas géré par nous car il est directement relié au serveur, c'est donc uniquement une ligne JS qui importe ce bandeau et qui s'occupe de la gestion des cookies sur le site

Par contre on peut indiquer la politique de confidentialité dans le footer, ca me paraitrait une bonne idée

**Comment by AyatoKirishima** [comment]
Oui oui, j'ai vu ça, mais du coup c'est pas réglementaires (j'pense que la plupart des gens s'en fichent btw)

**Comment by Spl4shh** [comment]
> Oui oui, j'ai vu ça, mais du coup c'est pas réglementaires (j'pense que la plupart des gens s'en fichent btw)

Je pense qu'il s'en fiche mais surtout, nous on peut pas vraiment gérer le principe de cookie, ou du moins, on délègue ca à l'hébergeur, ca fait une contrainte en moins.
Apres si tu es capable de faire, tu peux tjr test et je verrais si ca correspond à ce qu'on attend

**Comment by AyatoKirishima** [comment]
Y'a toujours Axceptio sinon, j'ai fait ça sur mon site, sinon, on laisse ça à l'hébergeur oui

**Comment by Dhoulnoun** [comment]
#50

**Comment by Spl4shh** [comment]
> #50

Va etre corriger courrant semaine prochaine au plus tard.
Le RGPD sera déjà plus correct

**Comment by Spl4shh** [comment]
@AyatoKirishima ? Il fallait pas faire la politique de confidentialité ?

**Comment by Spl4shh** [comment]
Non gérable de notre coté
