### ISSUE TITLE
[Page création de commande] - Refaire l'interface

### ISSUE THREAD

**Issue by AyatoKirishima** [GeanyDuMal/AMT#90]
+ il me faut les droits

**Comment by Spl4shh** [comment]
A faire dans la base de test en suivant la doc d'installation tout en bas de Command.md
Suite à ca, se créer un compte sur le site et s'assigner le "ROLE_ADMIN" manuellement, 
Sinon ne pas lancer les fixtures, et créer un compte, le premier compte créer a le role PRESIDENT qui equivaut au role admin

**Comment by AyatoKirishima** [comment]
Ou alors juste un screen de la page comme ça je fais une maquette et tu en fais ce que tu veux lol

**Comment by Spl4shh** [comment]
@AyatoKirishima Une date de prévue pour la maquette ou ce seras pas tout de suite ?

**Comment by Spl4shh** [comment]
Comprise dans #190
